{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: test-job
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "sleep 30" ]
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
