{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels: 
    rand: {{ .Values.job.rand }}
spec:
  template:
    spec:
      containers:
      - name: test-job-{{ .Values.job.rand }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "sleep 30" ]
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
